/**
 * Aset hasil ekspor Figma.
 * Jalankan `npm run assets` sekali untuk mengunduh semuanya ke /public/assets.
 */
export const A = {
  avatar: "/assets/avatar.png",
  badgeVerified: "/assets/badge-verified.png",
  badgeX: "/assets/badge-x.png",

  logoAlfagift: "/assets/logo-alfagift.png",
  logoBrawijaya: "/assets/logo-brawijaya.png",
  logoBinus: "/assets/logo-binus.png",
  logoNetwerk: "/assets/logo-netwerk.webp",
  logoGridbrid: "/assets/logo-gridbrid.webp",
  logoFastwork: "/assets/logo-fastwork.webp",
  logoJokiProyek: "/assets/logo-jokiproyek.webp",
  logoGoogle: "/assets/logo-google.webp",
  logoBcaDigital: "/assets/logo-bca-digital.webp",
  logoPopSurvey: "/assets/logo-popsurvey.webp",
  logoHology: "/assets/logo-hology.webp",

  apo1: "/assets/apo-waiting-trip.png",
  apo2: "/assets/apo-ongoing.png",
  apo3: "/assets/apo-ride-details-2.png",
  apo4: "/assets/apo-ride-details-1.png",
  apo5: "/assets/apo-ride-details-3.png",

  apoCover: "/assets/apo-cover.png",
  edunexCover: "/assets/edunex-cover.png",
  glidexaCover: "/assets/glidexa-cover.png",
  glidexaHero: "/assets/glidexa-hero.webp",
  glidexaWhy: "/assets/glidexa-why.webp",

  gx2Hero: "/assets/gx2-hero.webp",
  gx2Pillars: "/assets/gx2-pillars.webp",
  gx2Why: "/assets/gx2-why.webp",
  gx2Pricing: "/assets/gx2-pricing.webp",
  gx2Faq: "/assets/gx2-faq.webp",
  gx2Footer: "/assets/gx2-footer.webp",
  gx2Splash: "/assets/gx2-splash.webp",
  gx2Onb1: "/assets/gx2-onb1.webp",
  gx2Onb2: "/assets/gx2-onb2.webp",
  gx2Onb3: "/assets/gx2-onb3.webp",
  gx2Signin: "/assets/gx2-signin.webp",
  gx2Home: "/assets/gx2-home.webp",
  gx2Server: "/assets/gx2-server.webp",
  gx2Subs: "/assets/gx2-subs.webp",
  gx2Profile: "/assets/gx2-profile.webp",
  gx2Device: "/assets/gx2-device.webp",
  gx2History: "/assets/gx2-history.webp",
  gx2Language: "/assets/gx2-language.webp",
  gx2Help: "/assets/gx2-help.webp",
  gx2Forgot1: "/assets/gx2-forgot1.webp",
  gx2Forgot2: "/assets/gx2-forgot2.webp",
  gx2Forgot3: "/assets/gx2-forgot3.webp",

  matchVideo: "/assets/match-brand.mp4",
  matchPoster: "/assets/match-poster.webp",

  mewsVideo: "/assets/mews-mayangan.mp4",
  mewsPoster: "/assets/mews-mayangan-poster.webp",
  mewsDashboard: "/assets/mews-dashboard.webp",
  mewsAlert: "/assets/mews-alert.webp",
  mewsData: "/assets/mews-data.webp",
  mewsCuaca: "/assets/mews-cuaca.webp",
  mewsPerangkat: "/assets/mews-perangkat.webp",

  blogThumb: "/assets/blog-thumb.png",
  blogRafaetech: "/assets/blog-rafaetech.webp",
  blogRafaetechFull: "/assets/blog-rafaetech-full.webp",

  stripe: "/assets/stripe.svg",
  ornament: "/assets/ornament.svg",

  iconHome: "/assets/icon-home.svg",
  iconWork: "/assets/icon-work.svg",
  iconAward: "/assets/icon-award.svg",
  iconDoc: "/assets/icon-doc.svg",
  iconPhotos: "/assets/icon-photos.svg",
  iconChevron: "/assets/icon-chevron.svg",
} as const;
